### ISSUE TITLE
Regression in custom-transit-parser due to "Handle empty transit body params" fix

### ISSUE THREAD

**Issue by grzm** [pedestal/pedestal#458] opened 2016-08-29 01:33 UTC
# Description
The [Handle empty transit body params](https://github.com/pedestal/pedestal/commit/d948b6122bbe086562419efa36446f9bd330115c) fix introduced a regression where Transit-encoded bodies are no longer being parsed.

## Expected Behavior
Transit-encoded bodies should be parsed and assigned to `:transit-params` in the request map.

## Actual Behavior
When passed a Transit-encoded body with the appropriate content-type, the body is not parsed and not assigned to `:transit-params` in the request map.

## Steps to reproduce
I've put together a [test case repo](https://github.com/grzm/pedestal-transit-parser-available-bug/tree/0.5.0) with instructions how to reproduce. You can see the regression from Pedestal 0.5.0 to 0.5.1.

## Operating System (including version).

Mac OS X 10.10.5

## Your current Leiningen version (`lein --version`)

    λ lein --version
    Leiningen 2.6.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM

`[org.clojure/clojure "1.8.0"]` and `[org.clojure/clojure "1.9.0-alpha11"]`

## Pedestal version
  [io.pedestal/pedestal.service "0.5.1"]

**Comment by grzm** [comment] 2016-08-29 01:40
I know there are [tests for transit-params using the same values](https://github.com/pedestal/pedestal/blob/master/service/test/io/pedestal/http/body_params_test.clj#L91-L95) I am in the tests in the repo, and I don't see what's different between what the test existing test is doing and what I'm doing using `response-for`.

**Comment by ohpauleez** [comment] 2016-08-29 10:31
I've been looking into it this morning -- it's unclear is this is really a regression or just a bug with `response-for`, because it doesn't implement `.available` on the proxied ServletInputStream.  I'll report back later.

**Comment by grzm** [comment] 2016-08-29 11:07
Interesting! I looked at it from a running app using curl and can confirm that it works with both 0.5.0 and 0.5.1:
```
curl localhost:8080/transit -X GET -H "Content-Type: application/transit+json" -d '["^ ","~:b",2,"~:a",1]'
{:b 2, :a 1}
```

**Comment by ohpauleez** [comment] 2016-08-29 11:45
Excellent, thanks for the feedback!  I'll have a fix for this by the end of the day.

**Comment by ohpauleez** [comment] 2016-08-29 11:59
This should be fixed on master now.  Thanks!

**Closed by ohpauleez** 2016-08-29 11:59 UTC

**Comment by grzm** [comment] 2016-08-29 13:20
Thanks for the quick turnaround!

**Comment by grzm** [comment] 2016-08-29 13:36
Would you accept a test for this? Given this is a part of Pedestal that I'm using, I'd like to make sure we catch it if it breaks in the future.

**Comment by ohpauleez** [comment] 2016-08-29 14:07
I would happily accept a test for this.  I went to go add one but the interceptors are tested in isolation (directly via the interceptor chain execution), and the test-tests don't currently include `response-for` -- it's exercised elsewhere.

So if you find a good spot for it, or you want to ramp up some additional tests in test-test, that'd be great!

**Comment by grzm** [comment] 2016-08-29 19:44
Added one here: https://github.com/pedestal/pedestal/pull/461
