### ISSUE TITLE
ex-info's thrown by Pedestal contain problematic redundant data

### ISSUE THREAD

**Issue by ghadishayban** [pedestal/pedestal#640] opened 2020-01-23 19:34 UTC
# Description
ex-info's thrown by the interceptor chain contain data with two pieces of redundant information.  This redudancy causes huge output with the default exception printing machinery in clojure.core
This means that an ex-info with 2 chained causes (three exceptions total) will have 7 exceptions printed: 4 for the pedestal wrapper in front of the 3 exceptions, then the 3 exceptions printed _within the ex-data_.

The problematic info in ex-data:
1) `:exception`  -- this represents the cause, but it is already properly visible as the chained 
exception cause.  `pr` upon a exception from the interceptors will end up printing the cause twice, once as the outermost's cause, and once within the ex-data of the outermost exception.
2) the ex-data of the cause is re-merged in the top-level ex-data, which confuses the provenance (who threw that data?)

https://github.com/pedestal/pedestal/blob/621b6896aab6582499e0076bd9c73d5aeb01dae9/interceptor/src/io/pedestal/interceptor/chain.clj#L36-L41

## Expected Behavior
user exceptions have data, pedestal wraps an ex-info that chains the cause, with ex-data containing pedestal-specific augmentations

## Actual Behavior
`pr` of an interceptor-thrown exception

```
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "java.lang.NullPointerException in Interceptor :REDACTED - ",
   :data
   {:execution-id 4128,
    :stage :enter,
    :interceptor :REDACTED,
    :exception-type :java.lang.NullPointerException,
    :exception
    #error {:cause nil, :via [{:type java.lang.NullPointerException, :message nil, :at [java.util.UUID fromString "UUID.java" 192]}], :trace [[java.util.UUID fromString "UUID.java" 192] .....truncated

## Steps to reproduce
Throw an exception or ex-info in an interceptor :enter method, then `pr` the exception

# Environment

## Operating System (including version).
MacOS 10.14
## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
2.9.1
## Pedestal version
0.5.7

**Comment by ddeaguiar** [comment] 2020-01-23 19:43
Thanks for reporting this @ghadishayban. I agree that `:exception` is redundant. While I'm not opposed to removing it, backwards compatibility should be kept in mind. Any service implementation which depends on that data would need to change. Perhaps it's sufficient to remove this key and add a note to the ChangeLog. The reduction in log output is probably worth the cost.

@ohpauleez interested in your thoughts here.

**Comment by ohpauleez** [comment] 2020-01-23 19:44
This seems like intended behavior to me.  The ex-data is packed the way it is to allow machinery (not humans) to interpret the exception and take action.  The data (as presented in your example) would enable machine to react to the given interceptor, at the given stage, with a given exception.  In that regard, I don't think any of the information is redundant (the ex-info is a wrapper for an exception, and that exception is the target for action - it's not actually 'second' in the chain).

Packing the exception this way allows a supervisor to attempt to see all exceptions and take action as necessary.

Are you envisioning a different problem or perhaps a different solution?

**Comment by ohpauleez** [comment] 2020-01-23 19:46
Is this problematic because of logging?  Or does is it about obfuscating the root cause of an issue when at a REPL and working in dev mode?

**Comment by ddeaguiar** [comment] 2020-01-23 19:47
> Is this problematic because of logging? Or does is it about obfuscating the root cause of an issue when at a REPL and working in dev mode?

Based on my conversation with @ghadishayban, it has to do with logging.

**Comment by ddeaguiar** [comment] 2020-01-23 19:49
> Packing the exception this way allows a supervisor to attempt to see all exceptions and take action as necessary.
@ohpauleez but the cause is accessible via the `ExceptionInfo` instance. Is a separate key really necessary?

**Comment by ohpauleez** [comment] 2020-01-23 19:57
In the past, I've let a supervisor Interceptor clean uncaught exceptions before throwing.  In some systems, a separate supervisor ran the interceptor chain from a higher level of control and I've done the same there.

One idea is to provide a guide or some auxiliary functions to make this easier/clearer/convenient.
- - - - -

It isn't strictly necessary to capture `:exception` the way we're doing now, but in practice you almost always have to do this in a supervisor (because you want to pattern-match on the ex-data, or handle it as one logical collection/piece of data, etc.).  The supervisor looks at `ex-data` to see if it's a situation it knows about within the state machine that makes up the Interceptor chain.  If it does, it can attempt to rescue the request and potentially restart the chain/processing.  Pedestal really treats ExceptionInfo just as a throwable container for exception information, not as an exception itself.  We could consider making some changes here, but they will be breaking changes since Pedestal's own pattern-matching exception interceptor/supervisor also has these expectations.

I'm very interested to hear others' thoughts/experiences/approaches here.

**Comment by ddeaguiar** [comment] 2020-01-23 20:02
The [doc-string](https://github.com/pedestal/pedestal/blob/master/interceptor/src/io/pedestal/interceptor/error.clj#L20-L21) for `error-dispatch` calls out `:exception-type` but not `:exception`. While `:exception` is currently present, it's not clearly documented so perhaps it's not being used.

**Comment by ohpauleez** [comment] 2020-01-23 20:07
For those interested in a larger context- The X10 programming language was an inspiration in thinking through how best to convey exceptions across boundaries, but still work on them as if they were data.

**Comment by ghadishayban** [comment] 2020-01-23 21:01
ExceptionInfo's are already machine-readable. For example, `clojure.core/Throwable->map` processes them generically.  If something encounters an `ex-info`, you can call ex-data to get the data, and `ex-cause` to get the cause, or you can call `Throwable->map` to shred it into parts.

`error-dispatch` dispatches calls out: `:execution-id`, `:stage`, `:interceptor`, `:exception-type` to match upon.

**Comment by ddeaguiar** [comment] 2020-01-24 19:56
After thinking about this further, I've concluded that since `:exception` is part of the public data interface for exceptions caught by the interceptor chain machinery, it's best to leave it in place. Backwards compatibility trumps perceived redundancy.

That being said, we could do a better job communicating how they could be processed. The [Error handling](http://pedestal.io/reference/error-handling) reference should be updated to include the `:exception` key, address some doc issues (Pedestal does not binds a wrapped exception to `:io.pedestal.interceptor.chain/error`, not the raw exception) as well as recommendations on how to process exceptions for purposes like logging. I'll keep this issue open until I get those docs updated.

In the process of digging into this, I did spot a separate issue [here](https://github.com/pedestal/pedestal/blob/master/interceptor/src/io/pedestal/interceptor/chain.clj#L77). `(type (:exception ex))` should be `(type (:exception (ex-data ex)))` or `(-> ex :ex-data :exception :type)`.

**Comment by ghadishayban** [comment] 2020-04-20 17:17
One piece of missing data from the ex-info is the interceptor full name. The namespace is dropped intentionally.

The original motivation for this issue was making a summary of an exception to send to Honeycomb or write to a log.

**Comment by ddeaguiar** [comment] 2020-04-21 09:37
> One piece of missing data from the ex-info is the interceptor full name. The namespace is dropped intentionally.
> 
> The original motivation for this issue was making a summary of an exception to send to Honeycomb or write to a log.

@ghadishayban, based on the [source](https://github.com/pedestal/pedestal/blob/621b6896aab6582499e0076bd9c73d5aeb01dae9/interceptor/src/io/pedestal/interceptor/chain.clj#L33), the full name should be printed. It's using an [internal](https://github.com/pedestal/pedestal/blob/621b6896aab6582499e0076bd9c73d5aeb01dae9/interceptor/src/io/pedestal/interceptor/chain.clj#L29-L30) fn to do this. Are you seeing different behavior?

**Comment by ghadishayban** [comment] 2020-04-21 13:34
Yup thanks, I think I relayed a bad report.

**Comment by ddeaguiar** [comment] 2020-05-01 16:37
Closing this. The [docs](http://pedestal.io/reference/error-handling#_error_handling_and_logging) now provide guidance.

**Closed by ddeaguiar** 2020-05-01 16:37 UTC
Labels: discuss
