### ISSUE TITLE
Weird behavior with table syntax

### ISSUE THREAD

**Issue by mtsbarbosa** [pedestal/pedestal#725] opened 2022-10-02 15:49 UTC
# Description
When having such route patterns:
```clojure
#{["/users" :get (conj i/json-root-stack `get-users) :route-name :get-users]
             ["/users/:id" :get (conj i/json-root-stack `get-user) :route-name :get-user]
             ["/users" :post (conj i/json-stack `post-user) :route-name :post-users]
             ["/users/:id" :delete (conj i/json-root-stack `delete-user) :route-name :delete-user]
             ["/users/login" :post (conj i/json-stack `login-user) :route-name :login-user]}
```

## Expected Behavior
I was expecting the route
[POST] /users/login to be found and return 200

## Actual Behavior
[POST] /users/login returns 404 and route function login-user is not triggered

## Steps to reproduce
just add the table routes as above, and try to request /users/login

# Environment

## Operating System (including version).
Linux Mint 21 Vanessa

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.9.1 on Java 11.0.16 OpenJDK 64-Bit Server VM

## Pedestal version
0.5.10

**Comment by michalwilk123** [comment] 2022-10-09 20:08
I had the same issue. Changing the router parameter in service map to `:linear-search` fixed this. There is apparent bug in the :prefix-tree router implementation

**Comment by michalwilk123** [comment] 2022-10-09 20:35
related https://github.com/pedestal/pedestal/issues/726

**Comment by hlship** [comment] 2022-12-09 23:51
This does seem like a bug; at first I was going to point out that wildcards routes always "win" but that's not the case here.

**Comment by mtsbarbosa** [comment] 2023-04-02 20:16
I was able to reproduce it on `repl` if anyone interested:
```clojure
(require '[io.pedestal.http.route.prefix-tree :as p-tree])
(def ptree (-> nil
               (p-tree/insert "/users/:id" 1)
               (p-tree/insert "/users/login" 2)))

(p-tree/lookup ptree "/users/123")
=> {:path-params {:id "123"}, :payload #io.pedestal.http.route.prefix_tree.Payload{:routes [1]}}
(p-tree/lookup ptree "/users/login")
=> {:path-params {:id "login"}, :payload #io.pedestal.http.route.prefix_tree.Payload{:routes [1]}}
```

reason for it is here:
https://github.com/pedestal/pedestal/blob/318d3b57bc5c60ff15aab7f9aea0214ea1113f77/route/src/io/pedestal/http/route/prefix_tree.clj#L246
   
I guess the algorithm was designed to look for the first child
being a wild card `*` or `:something`, then to go for the others as @hlship mentioned

```clojure
(let [c (:children node)]
    (or (get c ":")
        (get c "*")
        (get c (char-key path segment-size))))
```

I am not sure if changing that we are sort of slowing down the algorithm or even moving towards making a linear-search-like out of that. So, a bit unclear to me if that's a bug, because of the algorithm's design.

**Comment by terjesb** [comment] 2023-04-04 08:48
@mtsbarbosa I think in your example, both of your routes are GETs? If that's the case, this is documented and by design for the prefix-router, ref http://pedestal.io/reference/routing-quick-reference:

> Wildcard routes always win over explicit paths in the same subtree. E.g., /path/:wild will always match, even if /path/user is defined

In the original example in this issue, the problem seems to be that this unexpectedly also seems to apply across different verbs. The expectation is that POST /path/user should win over DELETE or GET /path/:wild, also for the prefix-tree router. 

That being said, the doc above does say "always", which could be interpreted as independent of verb. But @hlship seems to confirm it's a bug.

**Comment by hlship** [comment] 2023-06-01 21:59
Here's some findings:

**Comment by ohpauleez** [comment] 2023-06-01 22:19
The tree router is a prefix tree based on the route.  Once a route matches, it uses a hash-map to see if there's a verb match.  Given this setup, perhaps it's easier to see why "wildcards always win" -- they are greedy in their matching within the prefix tree.

When the prefix-router was created, we identified other matching strategies that better balance expectations here, but their time and space complexity are difficult to reason about.  For example, you could keep all static routes in a hash-map or prefix-tree, and all wildcard routes in their own prefix tree -- on request you first try to match a static route and fallback to trying to match a wildcard route (I believe this is what retit does internally, for example).  This also matches the process the linear router follows (go through the sequence of static routes before going through a different sequence of wildcard routes)

### Using constraints within routes

It has always been a bad idea to put constraints in at the route level -- process constraints within your endpoint handler.

**Comment by hlship** [comment] 2023-06-01 22:53
Once could imaging that the prefix would map to a seq of routes, not a single one, ordered by specificity, and attempt to match each of them.  

That being said, I think there's a fundamental problem with having routes that `/user/:id` and `/user/logout` at the same time because what if the user's id actually is `logout`?  Or something more likely and more subtle. 

I'm leaving this with better documentation, and a clear test case that demonstrates the difference between prefix tree and linear routing.

**Comment by aredington** [comment] 2023-06-02 13:00
Agree with @ohpauleez on the problems of applying constraints in route checking. The root conflict here is only possible because verbs are not considered at the time that the wildcard prefix stem conflicts with the privileged token 'logout' in the route. We must maintain an NxM matches for N routes and M verbs. I'd like some assistance in reasoning through the consequences of inverting the priority of path and verb: apply the HTTP verb (which is always present, and has a narrow branching factor) first, and then apply a prefix-tree against the path (which is always present, and likely has a higher branching factor) **for that verb** posterior to verb matching.

I agree with @hlship that the use case related to the bug is treacherous, but the dangers of the example don't invalidate the problem of a route that should match the request not matching due to an implementation detail.

I believe that inverting verb and path should lead to an ability to generate prefix trees which require fewer distinct stems and intermediate nodes because only the prefixes which cluster by verb need to be differentiated in the tree, which seems like a win. But eager to hear of any other less beneficial consequences I'm ignoring.

**Comment by ohpauleez** [comment] 2023-06-02 13:57
Thanks everyone for throwing together some ideas to consider and helping illustrate the challenges in the design space (ala "what if there was a user named 'logout'").

A great bit of background here is the article, "40 years of Suffix Trees" from [ACM Communications; March 2016](https://dl.acm.org/doi/10.1145/2810036)

The utility of using a prefix-tree for routing is that redundant path segments get "compressed down" giving us a log-n match.  In one sense, the more overlap we have in the routes, the better off we'll do compared to something linear.  If you split on verb first, you don't have _a_ prefix tree, you have M trees (one for each verb) and you have duplicate path information across those different (and potentially sparse) trees.

@aredington's suggestion of leaning in to common tree-walk solutions (aggressively prune the search space) is a good one, but I think that's a different router altogether potentially and not one necessarily based on a prefix-tree.  There is tension here that a solution needs to do two different matches, one on routes and one of verbs -- I don't know of an encoding where verbs+routes get matched together, but I'm sure one exists.

Generally speaking, you want to match by the biggest discriminating characteristic first (to reduce the search space), which is another reason why the prefix-router does path then verb.

**Comment by hlship** [comment] 2023-06-02 14:42
Again, I think changing the current prefix tree router now is extremely risky due to the high probability of unforeseen consequences affecting existing applications. Still, Alex's idea is that we have one prefix tree per HTTP verb, and choosing the correct prefix tree is very cheap compared to navigating such a tree (which uses some amount of string comparisons, etc.).

**Comment by aredington** [comment] 2023-06-02 15:22
Trying to get at _problems_ by describing qualities of these circumstances:

- The current prefix tree finds one verb dispatch table per request.
- The prefix tree prioritizes wildcards ahead of static routes (documented)
- The _information gain_ of dispatching by path (two and three possible matches for `/users` and `/user/:token` respectively) is inferior to the _information gain_ of dispatching by verb (two, two, and one possible matches for `:get`, `:post`, and `:delete`).

Bullet 2 is documented and has provided Pedestal users structure that they are most likely leaning on right now, and altering it is most likely a breaking change.

Bullet 1 is likely to recharacterize performance of the prefix-tree if it is changed.

Bullet 3 is interesting but should probably be a different router to opt into rather than a change to the prefix-tree.

**Comment by hlship** [comment] 2024-01-05 21:46
Looking over the above, I don't see anything actionable beyond, perhaps, ongoing documentation improvements, or a new router.  In the meantime, I'm closing this issue.

**Closed by hlship** 2024-01-05 21:46 UTC
Labels: analyzing
