### ISSUE TITLE
SEVERE warnings when deploying a war using ClojureVarServlet to tomcat 8

### ISSUE THREAD

**Issue by dball** [pedestal/pedestal#438] opened 2016-06-03 14:48 UTC
When I use a war file using ClojureVarServlet in tomcat 8, I always get SEVERE log warnings of the form:

```
03-Jun-2016 09:37:34.782 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [clojure.lang.Var$1] (value [clojure.lang.Var$1@7c3ecc87]) and a value of type [clojure.lang.Var.Frame] (value [clojure.lang.Var$Frame@7d2113e4]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
03-Jun-2016 09:37:34.782 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [clojure.core.async.ThreadLocalRandom$1] (value [clojure.core.async.ThreadLocalRandom$1@7d6ffd1c]) and a value of type [clojure.core.async.ThreadLocalRandom] (value [clojure.core.async.ThreadLocalRandom@23700ebd]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
03-Jun-2016 09:37:34.782 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [clojure.lang.Var$1] (value [clojure.lang.Var$1@7c3ecc87]) and a value of type [clojure.lang.Var.Frame] (value [clojure.lang.Var$Frame@7d2113e4]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

This seems like a manifestation of the issue raised here in clojure core: http://dev.clojure.org/jira/browse/CLJ-1125

But it claims to have been fixed in clojure 1.6, and I'm using clojure 1.8.

I will investigate more deeply, but figured it would be reasonable to open a ticket in case someone with more experience in this area has guidance. It may be worth noting that I'm not doing anything interesting in my destroy fn other than stopping my application's stateful system resources. Specifically, I am not calling `(shutdown-agents)`, though perhaps I should?

**Comment by ohpauleez** [comment] 2016-06-03 14:57
Thanks for reporting @dball!  Keep us posted on any other developments.  I've seen similar problems Classloader juggling before, but I haven't personally seen these in servlet containers since the patch.

A few additional pieces of information would be helpful:  Can you look at the deps of you WAR and ensure that nothing is pulling in an older version of Clojure?  Can you let us know the exact Tomcat 8 version, and any steps we could take to create a reproduction?  I'll do my best to reproduce with our [WAR sample project](https://github.com/pedestal/pedestal/tree/master/samples/war-example).

**Comment by dball** [comment] 2016-06-03 15:07
Right on. Worth noting that there are also a bunch of INFO logs preceding the SEVERE warnings:

```03-Jun-2016 10:53:11.228 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
03-Jun-2016 10:53:11.229 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [clojure.core.async.timers/timeout-daemon] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
 clojure.core.async.impl.timers$timeout_worker.invokeStatic(timers.clj:60)
 clojure.core.async.impl.timers$timeout_worker.invoke(timers.clj:56)
 clojure.lang.AFn.run(AFn.java:22)
 java.lang.Thread.run(Thread.java:745)```

Which seem likely to be related.

I can confirm that clojure 1.8 is the only clojure in the webapp libs. I have the issue locally with tomcat-8.0.33 and on Elastic Beanstalk which claims to be running the same version (and is, incidentally, the only reason I'm faffing about with tomcat and its classloader which has been causing me varying amounts of pain for well over a decade now!)

I'll see if I can reproduce locally with your sample war project and, if not, see if I can create a sample repo that exhibits the problem.

I appreciate your prompt response. Hopefully we can get to the bottom of this forthwith.

**Comment by dball** [comment] 2016-06-03 19:11
I do now have a sample uberwar that exhibits at least one leak on shutdown:

```
03-Jun-2016 15:04:12.628 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [sample] appears to have started a thread named [clojure.core.async.timers/timeout-daemon] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
 clojure.core.async.impl.timers$timeout_worker.invokeStatic(timers.clj:60)
 clojure.core.async.impl.timers$timeout_worker.invoke(timers.clj:56)
 clojure.lang.AFn.run(AFn.java:22)
 java.lang.Thread.run(Thread.java:745)
```

It's 30M, I assembled it by hand, and I can share it. I'll see if I can continue to slim down the size by removing irrelevant libs, but in the meantime, would you like to take a look at it?

**Comment by dball** [comment] 2016-06-03 19:25
Briefly, it's much like the example war, but has this clojure file:

```
(ns sample.servlet
  (:require [io.pedestal.http]))

(defn init
  [_ _])

(defn destroy
  [_])

(defn service
  [_ request response])
```

and this web.xml:

```<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         version="3.0"
         metadata-complete="true">
  <description>Sample Service</description>
  <display-name>Sample Service</display-name>

  <!-- the Default servlet will serve static files & handle generic errors -->
  <servlet>
    <servlet-name>default</servlet-name>
    <servlet-class>org.apache.catalina.servlets.DefaultServlet</servlet-class>
    <init-param>
      <param-name>debug</param-name>
      <param-value>0</param-value>
    </init-param>
    <init-param>
      <param-name>listings</param-name>
      <param-value>false</param-value>
    </init-param>
    <init-param>
      <param-name>showServerInfo</param-name>
      <param-value>false</param-value>
    </init-param>
    <!-- http://stackoverflow.com/questions/809775/what-does-the-servlet-load-on-startup-value-signify -->
    <load-on-startup>1</load-on-startup>
  </servlet>

  <!-- the real meat - our servlet generated by Pedestal -->
  <servlet>
    <servlet-name>PedestalServlet</servlet-name>
    <servlet-class>io.pedestal.servlet.ClojureVarServlet</servlet-class>
    <init-param>
      <param-name>init</param-name>
      <param-value>sample.servlet/init</param-value>
    </init-param>
    <init-param>
      <param-name>service</param-name>
      <param-value>sample.servlet/service</param-value>
    </init-param>
    <init-param>
      <param-name>destroy</param-name>
      <param-value>sample.servlet/destroy</param-value>
    </init-param>
    <!-- http://stackoverflow.com/questions/809775/what-does-the-servlet-load-on-startup-value-signify -->
    <load-on-startup>2</load-on-startup>
  </servlet>

  <!-- allows us to serve up favicon and error messages when loading fails -->
  <servlet-mapping>
    <servlet-name>default</servlet-name>
    <url-pattern>/*</url-pattern>
  </servlet-mapping>

  <!-- route all /api/ requests to Pedestal (note that other requests will be ignored) -->
  <servlet-mapping>
    <servlet-name>PedestalServlet</servlet-name>
    <url-pattern>/sample/*</url-pattern>
  </servlet-mapping>

  <!-- TODO: figure out why this doesn't seem to actually work -->
  <welcome-file-list>
    <welcome-file>index.html</welcome-file>
  </welcome-file-list>

  <!-- provide top-level error handling so that Tomcat doesn't expose stack traces to end users -->
  <error-page>
    <error-code>404</error-code>
    <location>/errors/404.html</location>
  </error-page>
  <error-page>
    <location>/errors/generic.html</location>
  </error-page>

</web-app>```

I've also got my sample.war file down to ~6M if you'd like to peruse it directly.

**Comment by dball** [comment] 2016-06-03 19:26
The require 'io.pedestal.http is the necessary condition for getting the leak of the timeout-daemon.

**Comment by ohpauleez** [comment] 2016-06-06 11:26
Thanks for pulling together all the pieces, I'll dig in this week!

**Comment by hlship** [comment] 2023-04-28 22:13
This issue has been open for quite some time. We apologize if it has not received
the attention it deserves; given the amount of time that has passed, we are
focusing on other urgent issues.  We are closing this issue for the meantime, please re-open 
if it is still relevant.

**Closed by hlship** 2023-04-28 22:13 UTC
Labels: analyzing
