### ISSUE TITLE
:transit-params not available during testing with response-for

### ISSUE THREAD

**Issue by rauhs** [pedestal/pedestal#479] opened 2016-10-22 05:58 UTC
# Description
Commit d948b6122bbe086562419efa36446f9bd330115c seems to break transit parsing when testing with `response-for`. The problem is that `(.available (:body req))` returns 0, even though there is data in the stream. Maybe there is something wrong with how the body stream gets constructed for testing?

## Steps to reproduce
This code should reproduce it. There is parts you can uncomment and see the working version.
```clojure
(def body-parser
  {#"^application/transit\+json"
   (fn [{:keys [body] :as req}]
     ;; Calling slurp on body here works but will trigger a EOFException since the stream is
     ;; then consumed.
     (assoc req
       :body-debug [(.available body)]
       :transit-params (transit/read (transit/reader body :json))))})

(def routes
  (table/table-routes
    [["/a/"
      :post [ ;; Uncommenting the default parser and the transit params are not available:
             ;#_
                 (body-params/body-params)
             #_(body-params/body-params body-parser)

             #(-> {:status 200
                   :body (select-keys % [:transit-params :body-debug])})]
      :route-name :route/a]]))

(io.pedestal.test/response-for
  (-> {::pedestal/routes routes
       ::pedestal/type :immutant}
      pedestal/default-interceptors
      pedestal/dev-interceptors
      pedestal/service-fn
      ::pedestal/service-fn)
  "POST" "/a/"
  :body "[\"^ \",\"~:a\",\"~:b\"]" ;; {:a :b}
  :headers {"Content-Type" "application/transit+json;UTF-8"})
```
## Operating System (including version).
Linux sky 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## Pedestal version
0.5.1

**Comment by ohpauleez** [comment] 2016-10-25 19:07
Thanks @rauhs -- I started working on this issue.  Someone else in Cognitect stumbled on it as well, so I should have a fix on master soon.

**Comment by ohpauleez** [comment] 2016-10-25 20:36
This is fixed on master.  This is a duplicate of #458

**Closed by ohpauleez** 2016-10-25 20:36 UTC
