### ISSUE TITLE
CORS interceptor should provide an :error interceptor

### ISSUE THREAD

**Issue by winterscar** [pedestal/pedestal#736] opened 2023-03-15 12:22 UTC
# Description

CORS interceptor does not run after exceptions. This means that if one of your routes throws, instead of getting a 500 error, the browser shows a CORS error instead. Super confusing!

## Expected Behavior

Return correct cors `Access-Control-Allow-Origin` header even after an exception

## Actual Behavior

Because the code that adds the `Access-Control-Allow-Origin` is an `:after` interceptor, errors in any request cause the header to not be added correctly

## Steps to reproduce
1. Run this code in a REPL:
```clj
(require '[io.pedestal.http :as server])

(defn mk-err [_] (throw (Exception. "test")))

(def server
(-> {::server/type :jetty
       ::server/port 7123
       ::server/join? false
       ::server/allowed-origins {:creds true :allowed-origins (constantly true)}
       ::server/routes #{["/err" :get [`mk-err]]}} 
      server/default-interceptors
      server/dev-interceptors
      server/create-server
      server/start)

```
2. Open a browser tab on `https://google.com` and in the dev console, run the following code:
```js
let z = await fetch("http://localhost:7123/err")
```

You would expect to recieve an HTTP 500 error, but a CORS error is present instead.

# Environment

## Operating System (including version).
Mac OS 13.1
## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
`Leiningen 2.10.0 on Java 19.0.1 OpenJDK 64-Bit Server VM`
## Pedestal version
`0.5.11-beta-1`

**Comment by mtsbarbosa** [comment] 2023-04-03 19:36
Can you show the error you have pls?

because I tried your code, and got blocked on google itself, I guess it does not even forward the request to the server because of the origin

if your code reach the cors interceptor at least, you might find a log like these:
```bash
#allowed bellow:
INFO  io.pedestal.http.cors  - {:msg "cors request processing", :origin "", :allowed true, :line 84}

#forbiden bellow:
INFO  io.pedestal.http.cors  - {:msg "cors request processing", :origin "", :allowed nil, :line 84}
```

**Comment by hlship** [comment] 2024-01-05 19:44
I'm not sure I understand ... why would you want the header on a 500 response?  Does that even mean anything?

**Comment by hlship** [comment] 2024-01-05 19:46
Without dev interceptors:

```
> curl -i http://localhost:7123/err
HTTP/1.1 500 Server Error
Date: Fri, 05 Jan 2024 19:44:45 GMT
Content-Type: text/plain
Transfer-Encoding: chunked

Internal server error: exception%
```

With dev interceptors:

```
> curl -i http://localhost:7123/err
HTTP/1.1 500 Server Error
Date: Fri, 05 Jan 2024 19:45:34 GMT
Content-Type: text/plain
Transfer-Encoding: chunked

Error processing request!
Exception:


                                               java.lang.Thread.run                     Thread.java:  833
          org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run           QueuedThreadPool.java: 1149
     org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob           QueuedThreadPool.java: 1194
              org.eclipse.jetty.util.thread.QueuedThreadPool.runJob           QueuedThreadPool.java:  969
               org.eclipse.jetty.io.SelectableChannelEndPoint$1.run  SelectableChannelEndPoint.java:   53
                         org.eclipse.jetty.io.FillInterest.fillable               FillInterest.java:  100
     org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded         AbstractConnection.java:  314
                 org.eclipse.jetty.server.HttpConnection.onFillable             HttpConnection.java:  287
                        org.eclipse.jetty.server.HttpChannel.handle                HttpChannel.java:  501
                      org.eclipse.jetty.server.HttpChannel.dispatch                HttpChannel.java:  753
  org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch                HttpChannel.java: 1598
                             org.eclipse.jetty.server.Server.handle                     Server.java:  563
             org.eclipse.jetty.server.handler.HandlerWrapper.handle             HandlerWrapper.java:  122
              org.eclipse.jetty.server.handler.ScopedHandler.handle              ScopedHandler.java:  129
            org.eclipse.jetty.server.handler.ContextHandler.doScope             ContextHandler.java: 1303
           org.eclipse.jetty.server.handler.ScopedHandler.nextScope              ScopedHandler.java:  174
                   org.eclipse.jetty.servlet.ServletHandler.doScope             ServletHandler.java:  484
           org.eclipse.jetty.server.handler.ScopedHandler.nextScope              ScopedHandler.java:  176
           org.eclipse.jetty.server.handler.ContextHandler.doHandle             ContextHandler.java: 1381
          org.eclipse.jetty.server.handler.ScopedHandler.nextHandle              ScopedHandler.java:  221
                  org.eclipse.jetty.servlet.ServletHandler.doHandle             ServletHandler.java:  529
                     org.eclipse.jetty.servlet.ServletHolder.handle              ServletHolder.java:  764
                         io.pedestal.http.servlet.FnServlet/service                     servlet.clj:   28
io.pedestal.http.impl.servlet-interceptor/interceptor-service-fn/fn         servlet_interceptor.clj:  364
                              io.pedestal.interceptor.chain/execute                       chain.clj:  413
                              io.pedestal.interceptor.chain/execute                       chain.clj:  403
                            io.pedestal.interceptor.chain/enter-all                       chain.clj:  236
                          io.pedestal.interceptor.chain/process-all                       chain.clj:  188
                                                                ...
                                        clojure.core/with-bindings*                        core.clj: 1990 (repeats 2 times)
                                                 clojure.core/apply                        core.clj:  667
                                                                ...
                       io.pedestal.interceptor.chain/process-all/fn                       chain.clj:  190
             io.pedestal.interceptor.chain/process-all-with-binding                       chain.clj:  171
                                io.pedestal.interceptor.chain/try-f                       chain.clj:   57
                             io.pedestal.interceptor/eval2705/fn/fn                 interceptor.clj:   47
                                                        user/mk-err                        user.clj:   26
       java.lang.Exception: test
clojure.lang.ExceptionInfo: java.lang.Exception in Interceptor  - test
    exception-type: :java.lang.Exception
      execution-id: 3
       interceptor: nil
             stage: :enter
```

**Comment by hlship** [comment] 2024-01-05 19:49
I'm testing against 0.7.0, but I don't think any of this has changed since 0.5.x.

I'm going to close this until it is reproducable.

**Closed by hlship** 2024-01-05 19:49 UTC
